### ISSUE TITLE
f-string unmatched error in scrtypes.py

### ISSUE THREAD

**Issue by pay-87** [Green-Bat/srcomapipy#1]
hey what's up! I meant to try your library today but encountered an f-string: unmatched error.
here is the log:

```
Traceback (most recent call last):
  File "C:\Users\Christoph\PycharmProjects\TwitchBot\paybot.py", line 7, in <module>
    from commands import setup as setup_commands
  File "C:\Users\Christoph\PycharmProjects\TwitchBot\commands.py", line 6, in <module>
    from srcomapipy.srcomapipy import SRC
  File "C:\Users\Christoph\.virtualenvs\pythonProject-nbyF2Lse\Lib\site-packages\srcomapipy\srcomapipy.py", line 4, in <module>
    from .srctypes import *
  File "C:\Users\Christoph\.virtualenvs\pythonProject-nbyF2Lse\Lib\site-packages\srcomapipy\srctypes.py", line 14
    self.message = f"{code}: {data["message"]} ({uri}) "
                                    ^^^^^^^
SyntaxError: f-string: unmatched '['
```

Maybe you can have a look at it! Take care

**Comment by Green-Bat** [comment]
Fixed this in the latest version

**Comment by pay-87** [comment]
Awesome, thanks!
